from dataclasses import dataclass, field
from typing import Dict
import numpy as np


@dataclass
class SemanticTask:
    """
    A semantic communication task generated by a terminal.

    Attributes
    ----------
    user_id:
        Source terminal ID.
    complexity:
        Task difficulty. Higher values mean that more tokens are needed to
        achieve the same semantic accuracy.
    urgency:
        Urgency weight. Higher values indicate stronger latency sensitivity.
    min_tokens:
        Lower bound of token allocation.
    max_tokens:
        Upper bound of token allocation.
    """

    user_id: int
    complexity: float
    urgency: float
    min_tokens: int
    max_tokens: int


@dataclass
class UserTerminal:
    user_id: int

    def generate_task(self, rng: np.random.Generator, min_tokens: int, max_tokens: int) -> SemanticTask:
        complexity = float(rng.uniform(0.7, 1.5))
        urgency = float(rng.uniform(0.5, 1.5))
        return SemanticTask(
            user_id=self.user_id,
            complexity=complexity,
            urgency=urgency,
            min_tokens=min_tokens,
            max_tokens=max_tokens,
        )


@dataclass
class EdgeNode:
    """
    Edge computing node in the computing power network.

    token_rate:
        Token processing capability, measured by token/s.
    load:
        Current normalized load in [0, 1].
    """

    node_id: int
    token_rate: float
    load: float = 0.0

    def effective_token_rate(self) -> float:
        return self.token_rate * max(0.05, 1.0 - self.load)

    def processing_delay(self, tokens: int, task_complexity: float) -> float:
        required_tokens = tokens * task_complexity
        return required_tokens / self.effective_token_rate()

    def update_load(self, tokens: int, decay: float = 0.85) -> None:
        injected_load = min(0.35, tokens / max(self.token_rate, 1.0))
        self.load = float(np.clip(decay * self.load + injected_load, 0.0, 0.98))


@dataclass
class ChannelState:
    """
    Wireless/fronthaul channel state from each user to each edge node.

    snr_db_matrix:
        Matrix with shape [num_users, num_edge_nodes].
    """

    snr_db_matrix: np.ndarray

    def snr_db(self, user_id: int, node_id: int) -> float:
        return float(self.snr_db_matrix[user_id, node_id])


@dataclass
class ScheduleDecision:
    user_id: int
    node_id: int
    tokens: int
    metadata: Dict[str, float] = field(default_factory=dict)
